version: '3'
services:
  main:
    build:
        context: .
        args:
            - http_proxy
            - https_proxy
            - no_proxy
    image: cubeearth/echoservice
    ports:
    - 8084:8080
